name: Autochecker

# Run every day at 2AM
on:
  schedule:
    - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: src

      - name: Run script
        id: checker
        run: ./src/CheckModuleData.ps1
